/* eslint-disable no-undef */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class", // 👈 Add this line to enable class-based dark mode
  content: [
    "./index.html",
    "./node_modules/flowbite-react/lib/**/*.{js,ts}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    colors: {
      trans_main: "#FFCC00",
      trans_main_hover: "#E6B800",
      trans_primary: "#333333",
      trans_secondary: "#A4A4A4",
      trans_white: "#FFFFFF",
      trans_bg: "#f8f8f8",
      primary: {
        50: "#fffbea",
        100: "#fff3c4",
        200: "#ffe58a",
        300: "#ffd85c",
        400: "#ffcc2e",
        500: "#FFCC00",
        600: "#d49f00",
        700: "#b38600",
        800: "#8f6a00",
        900: "#6b5000",
      },
    },
    fontFamily: {
      sans: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      body: [
        "Inter",
        "ui-sans-serif",
        "system-ui",
        "-apple-system",
        "system-ui",
        "Segoe UI",
        "Roboto",
        "Helvetica Neue",
        "Arial",
        "Noto Sans",
        "sans-serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Noto Color Emoji",
      ],
      mono: [
        "ui-monospace",
        "SFMono-Regular",
        "Menlo",
        "Monaco",
        "Consolas",
        "Liberation Mono",
        "Courier New",
        "monospace",
      ],
      bruno: ['"Bruno Ace SC"', "sans-serif"],
    },
    extend: {
      keyframes: {
        moveBox: {
          "0%": { transform: "translateX(-50px) rotate(0deg)", opacity: "0.2" },
          "20%": { opacity: "1" },
          "100%": {
            transform: "translateX(400px) rotate(360deg)",
            opacity: "0",
          },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        moveBox: "moveBox 6s linear infinite",
        "slide-down": "slideDown 0.2s ease-out",
        "slide-up": "slideUp 0.2s ease-out",
        "fade-in": "fadeIn 0.3s ease-in",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [require("flowbite/plugin")],
}
